Repository PDA-5th-Team5/BE, pull requests merged in 2025-02, with the labels that each got.

#2 [settings] Jenkins CI / CD 구축
  .gitignore
  Jenkinsfile
  README.md
  build.gradle
  docker-compose.yml
  src/api-gateway/Dockerfile
  src/eureka-server/Dockerfile
  src/snowflake-service/Dockerfile
  src/stock-service/Dockerfile
  src/user-service/Dockerfile
  src/util-service/Dockerfile
Labels: fix 🐞, settings :hammer_and_wrench:

#5 fix(#3): Jenkinsfile 수정
  Jenkinsfile
Labels: fix 🐞

#6 fix(#3): Jenkinsfile 수정
  Jenkinsfile
Labels: fix 🐞

#7 fix(#3): Jenkinsfile 수정
  Jenkinsfile
Labels: fix 🐞

#9 fix(#3): Jenkinsfile, Dockerfile 수정
  Jenkinsfile
  src/snowflake-service/Dockerfile
Labels: fix 🐞

#10 fix(#3): Jenkinsfile 수정
  Jenkinsfile
Labels: fix 🐞

#11 fix(#3): Jenkinsfile 수정
  Jenkinsfile
Labels: fix 🐞

#12 fix(#3): Dockerfile, build.gradle 수정
  build.gradle
  src/util-service/Dockerfile
Labels: fix 🐞

#17 Fix/#3 fix jenkinsfile
  .gitignore
  Jenkinsfile
  build.gradle
  docker-compose.yml
  src/api-gateway/src/main/java/com/pda/apigateway/ApiGatewayApplication.java
  src/api-gateway/src/main/resources/application.properties
  src/eureka-server/src/main/java/com/pda/eurekaserver/EurekaServerApplication.java
  src/eureka-server/src/main/resources/application.properties
  src/snowflake-service/src/main/resources/application.properties
  src/stock-service/src/main/resources/application.properties
  src/user-service/src/main/resources/application.properties
  src/util-service/src/main/resources/application.properties
Labels: fix 🐞, chore 😊

#19 Fix/#18 fix dockerfile jenkinsfile
  Jenkinsfile
  src/api-gateway/Dockerfile
  src/eureka-server/Dockerfile
  src/snowflake-service/Dockerfile
  src/stock-service/Dockerfile
  src/user-service/Dockerfile
Labels: fix 🐞

#27 pr feat/#23-portfolio-setup
  portfolio-service/src/main/java/com/pda/portfolioservice/controller/PortfolioController.java
  portfolio-service/src/main/java/com/pda/portfolioservice/entity/MyPortfolio.java
  portfolio-service/src/main/java/com/pda/portfolioservice/entity/SharePortfolio.java
  portfolio-service/src/main/java/com/pda/portfolioservice/entity/SharePortfolioComment.java
  portfolio-service/src/main/java/com/pda/portfolioservice/feign/StockServiceClient.java
  portfolio-service/src/main/java/com/pda/portfolioservice/feign/UserServiceClient.java
  portfolio-service/src/main/java/com/pda/portfolioservice/repository/PortfolioRepository.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioService.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioServiceImpl.java
Labels: feat ✨

#28 pr feat/#12-user-setup
  user-service/src/main/java/com/pda/userservice/controller/UserController.java
  user-service/src/main/java/com/pda/userservice/dto/CustomUserDetails.java
  user-service/src/main/java/com/pda/userservice/dto/JoinDTO.java
  user-service/src/main/java/com/pda/userservice/entity/User.java
  user-service/src/main/java/com/pda/userservice/enums/UserType.java
  user-service/src/main/java/com/pda/userservice/feign/PortfolioServiceClient.java
  user-service/src/main/java/com/pda/userservice/feign/StockServiceClient.java
  user-service/src/main/java/com/pda/userservice/repository/UserRepository.java
  user-service/src/main/java/com/pda/userservice/service/UserService.java
  user-service/src/main/java/com/pda/userservice/service/UserServiceImpl.java
  user-service/src/main/resources/application.properties
Labels: feat ✨

#33 pr feat/#29-로그인 구현
  build.gradle
  eureka-server/src/main/resources/application.properties
  user-service/src/main/java/com/pda/userservice/config/SecurityConfig.java
  user-service/src/main/java/com/pda/userservice/controller/UserController.java
  user-service/src/main/java/com/pda/userservice/dto/CustomUserDetails.java
  user-service/src/main/java/com/pda/userservice/dto/JoinDTO.java
  user-service/src/main/java/com/pda/userservice/dto/request/JoinDTO.java
  user-service/src/main/java/com/pda/userservice/entity/Refresh.java
  user-service/src/main/java/com/pda/userservice/entity/User.java
  user-service/src/main/java/com/pda/userservice/enums/UserType.java
  user-service/src/main/java/com/pda/userservice/jwt/CustomLogoutFilter.java
  user-service/src/main/java/com/pda/userservice/jwt/JWTFilter.java
  user-service/src/main/java/com/pda/userservice/jwt/JWTUtil.java
  user-service/src/main/java/com/pda/userservice/jwt/LoginFilter.java
  user-service/src/main/java/com/pda/userservice/repository/RefreshRepository.java
  user-service/src/main/java/com/pda/userservice/repository/UserRepository.java
  user-service/src/main/java/com/pda/userservice/service/CustomUserDetailsService.java
  user-service/src/main/java/com/pda/userservice/service/UserService.java
  user-service/src/main/java/com/pda/userservice/service/UserServiceImpl.java
  user-service/src/main/resources/application.properties
Labels: feat ✨

#39 pr feat/#36-API 게이트웨이 모든 연결 허용 설정
  api-gateway/src/main/java/com/pda/apigateway/config/SecurityConfig.java
  build.gradle
Labels: feat ✨

#48 pr feat/#47-openfeign 예제 구현(stock -> user)
  stock-service/src/main/java/com/pda/stockservice/StockServiceApplication.java
  stock-service/src/main/java/com/pda/stockservice/controller/StockController.java
  stock-service/src/main/java/com/pda/stockservice/feign/UserServiceClient.java
  stock-service/src/main/resources/application.properties
  user-service/src/main/java/com/pda/userservice/controller/UserController.java
  user-service/src/main/java/com/pda/userservice/dto/response/NicknameResponseDTO.java
  user-service/src/main/java/com/pda/userservice/service/UserService.java
  user-service/src/main/java/com/pda/userservice/service/UserServiceImpl.java
  user-service/src/main/resources/application.properties
  util-service/src/main/java/com/pda/utilservice/response/code/resultCode/ErrorStatus.java
Labels: feat ✨
