Repository PDA-5th-Team5/BE, pull requests merged in 2025-03, with the labels that each got.

#49 pr feat/#34-포트폴리오 관련 API 구현
  portfolio-service/src/main/java/com/pda/portfolioservice/PortfolioServiceApplication.java
  portfolio-service/src/main/java/com/pda/portfolioservice/controller/PortfolioController.java
  portfolio-service/src/main/java/com/pda/portfolioservice/dto/request/SharePortfolioCommentRequestDTO.java
  portfolio-service/src/main/java/com/pda/portfolioservice/dto/response/MyPortfolioTitleResponseDTO.java
  portfolio-service/src/main/java/com/pda/portfolioservice/dto/response/ShareMyPortfolioResponseDTO.java
  portfolio-service/src/main/java/com/pda/portfolioservice/dto/response/SharePortfolioCommentResponseDTO.java
  portfolio-service/src/main/java/com/pda/portfolioservice/entity/SharePortfolio.java
  portfolio-service/src/main/java/com/pda/portfolioservice/entity/SharePortfolioComment.java
  portfolio-service/src/main/java/com/pda/portfolioservice/feign/StockServiceClient.java
  portfolio-service/src/main/java/com/pda/portfolioservice/feign/UserServiceClient.java
  portfolio-service/src/main/java/com/pda/portfolioservice/repository/MyPortfolioRepository.java
  portfolio-service/src/main/java/com/pda/portfolioservice/repository/PortfolioRepository.java
  portfolio-service/src/main/java/com/pda/portfolioservice/repository/SharePortfolioCommentRepository.java
  portfolio-service/src/main/java/com/pda/portfolioservice/repository/SharePortfolioRepository.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioService.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioServiceImpl.java
  stock-service/src/main/java/com/pda/stockservice/dto/response/StockInfoResponseDTO.java
  stock-service/src/main/java/com/pda/stockservice/entity/Stock.java
  stock-service/src/main/java/com/pda/stockservice/enums/Market.java
  stock-service/src/main/java/com/pda/stockservice/enums/Sectors.java
  stock-service/src/main/java/com/pda/stockservice/repository/StockStatRepository.java
  util-service/src/main/java/com/pda/utilservice/response/code/resultCode/ErrorStatus.java
Labels: feat ✨, fix 🐞

#59 pr feat/#54-JWT 토큰에서 유저 아이디 추출
  stock-service/src/main/java/com/pda/stockservice/controller/StockController.java
  stock-service/src/main/java/com/pda/stockservice/repository/StockStatRepository.java
  user-service/src/main/java/com/pda/userservice/config/SecurityConfig.java
  user-service/src/main/java/com/pda/userservice/jwt/LoginFilter.java
  user-service/src/main/java/com/pda/userservice/service/UserServiceImpl.java
  util-service/src/main/java/com/pda/utilservice/jwt/JWTUtil.java
Labels: feat ✨

#62 pr feat/#60-getUserId 구현
  portfolio-service/src/main/resources/application.properties
  stock-service/src/main/resources/application.properties
  util-service/src/main/java/com/pda/utilservice/jwt/JWTUtil.java
Labels: feat ✨

#63 feat/#60-getBearerUserId 구현
  user-service/src/main/java/com/pda/userservice/controller/UserController.java
  util-service/src/main/java/com/pda/utilservice/jwt/JWTUtil.java
Labels: feat ✨

#66 "feat(#64): 관심종목 추가 userid 가져오기"
  stock-service/src/main/java/com/pda/stockservice/controller/StockController.java
  stock-service/src/main/java/com/pda/stockservice/service/StockService.java
  stock-service/src/main/java/com/pda/stockservice/service/StockServiceImpl.java
Labels: feat ✨

#67 "feat(#64): 관심종목 추가 userid 가져오기"
  stock-service/src/main/java/com/pda/stockservice/service/StockService.java
  stock-service/src/main/java/com/pda/stockservice/service/StockServiceImpl.java
Labels: feat ✨

#68 pr feat/#65-로그인 응답 형식 수정
  stock-service/src/main/java/com/pda/stockservice/controller/StockController.java
  user-service/src/main/java/com/pda/userservice/controller/UserController.java
  user-service/src/main/java/com/pda/userservice/dto/response/LoginResponseDTO.java
  user-service/src/main/java/com/pda/userservice/jwt/CustomLogoutFilter.java
  user-service/src/main/java/com/pda/userservice/jwt/LoginFilter.java
  user-service/src/main/java/com/pda/userservice/service/UserService.java
  user-service/src/main/java/com/pda/userservice/service/UserServiceImpl.java
Labels: feat ✨

#74 pr Fix/#50 get portfolio api
  .DS_Store
  portfolio-service/src/main/java/com/pda/portfolioservice/PortfolioServiceApplication.java
  portfolio-service/src/main/java/com/pda/portfolioservice/controller/PortfolioController.java
  portfolio-service/src/main/java/com/pda/portfolioservice/dto/request/SharePortfolioCommentRequestDTO.java
  portfolio-service/src/main/java/com/pda/portfolioservice/dto/response/ImportSharePortfolioResponseDTO.java
  portfolio-service/src/main/java/com/pda/portfolioservice/dto/response/PortfolioSummaryResponseDTO.java
  portfolio-service/src/main/java/com/pda/portfolioservice/dto/response/SharePortfolioCommentResponseDTO.java
  portfolio-service/src/main/java/com/pda/portfolioservice/dto/response/SharePortfolioListResponseDTO.java
  portfolio-service/src/main/java/com/pda/portfolioservice/dto/response/SharePortfolioSummaryResponseDTO.java
  portfolio-service/src/main/java/com/pda/portfolioservice/entity/MyPortfolio.java
  portfolio-service/src/main/java/com/pda/portfolioservice/entity/SharePortfolio.java
  portfolio-service/src/main/java/com/pda/portfolioservice/entity/SharePortfolioComment.java
  portfolio-service/src/main/java/com/pda/portfolioservice/feign/StockServiceClient.java
  portfolio-service/src/main/resources/application.properties
  stock-service/src/main/java/com/pda/stockservice/service/StockServiceImpl.java
Labels: fix 🐞

#78 Feat/#56 get comment
  stock-service/src/main/java/com/pda/stockservice/StockServiceApplication.java
  stock-service/src/main/java/com/pda/stockservice/controller/StockController.java
  stock-service/src/main/java/com/pda/stockservice/dto/response/CommentResponseDTO.java
  stock-service/src/main/java/com/pda/stockservice/dto/response/CompetitorsResponseDTO.java
  stock-service/src/main/java/com/pda/stockservice/dto/response/NicknameResponseDTO.java
  stock-service/src/main/java/com/pda/stockservice/entity/StockComment.java
  stock-service/src/main/java/com/pda/stockservice/feign/UserServiceClient.java
  stock-service/src/main/java/com/pda/stockservice/repository/StockCommentRepository.java
  stock-service/src/main/java/com/pda/stockservice/repository/StockRepository.java
  stock-service/src/main/java/com/pda/stockservice/service/StockService.java
  stock-service/src/main/java/com/pda/stockservice/service/StockServiceImpl.java
  user-service/src/main/java/com/pda/userservice/controller/UserController.java
Labels: feat ✨

#80 "feat(#79): StockCommentRepository충돌해결"
  stock-service/src/main/java/com/pda/stockservice/repository/StockCommentRepository.java
  stock-service/src/main/java/com/pda/stockservice/service/StockServiceImpl.java
Labels: fix 🐞

#82 pr Feat/#73 login connect portfolio api
  portfolio-service/src/main/java/com/pda/portfolioservice/controller/PortfolioController.java
  portfolio-service/src/main/java/com/pda/portfolioservice/dto/response/NicknameResponseDTO.java
  portfolio-service/src/main/java/com/pda/portfolioservice/dto/response/SharePortfolioCommentResponseDTO.java
  portfolio-service/src/main/java/com/pda/portfolioservice/entity/SharePortfolioComment.java
  portfolio-service/src/main/java/com/pda/portfolioservice/feign/UserServiceClient.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioService.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioServiceImpl.java
  portfolio-service/src/main/resources/application.properties
  stock-service/src/main/java/com/pda/stockservice/repository/StockCommentRepository.java
  stock-service/src/main/java/com/pda/stockservice/service/StockService.java
  stock-service/src/main/java/com/pda/stockservice/service/StockServiceImpl.java
  stock-service/src/main/resources/application.properties
Labels: fix 🐞

#88 "feat(#87): 관심종목 삭제api에서 token에서id 가져오기"
  stock-service/src/main/java/com/pda/stockservice/controller/StockController.java
  stock-service/src/main/java/com/pda/stockservice/service/StockService.java
  stock-service/src/main/java/com/pda/stockservice/service/StockServiceImpl.java
Labels: feat ✨

#90 pr Feat/#83 my portfolio title share delete
  portfolio-service/src/main/java/com/pda/portfolioservice/controller/PortfolioController.java
  portfolio-service/src/main/java/com/pda/portfolioservice/repository/PortfolioRepository.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioService.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioServiceImpl.java
Labels: feat ✨, fix 🐞

#92 "feat(#85): 종목 댓글 수정api"
  stock-service/src/main/java/com/pda/stockservice/controller/StockController.java
  stock-service/src/main/java/com/pda/stockservice/entity/StockComment.java
  stock-service/src/main/java/com/pda/stockservice/repository/StockCommentRepository.java
  stock-service/src/main/java/com/pda/stockservice/service/StockService.java
  stock-service/src/main/java/com/pda/stockservice/service/StockServiceImpl.java
Labels: feat ✨

#94 pr feat/#69-user 모듈 api 구현
  portfolio-service/src/main/java/com/pda/portfolioservice/controller/PortfolioController.java
  portfolio-service/src/main/java/com/pda/portfolioservice/dto/response/MyPortfolioCommentsResponseDTO.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioService.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioServiceImpl.java
  stock-service/src/main/java/com/pda/stockservice/config/RedisConfig.java
  stock-service/src/main/java/com/pda/stockservice/controller/StockController.java
  stock-service/src/main/java/com/pda/stockservice/dto/response/FixedStockSnowflakeResponseDTO.java
  stock-service/src/main/java/com/pda/stockservice/dto/response/MyStockCommentsResponseDTO.java
  stock-service/src/main/java/com/pda/stockservice/dto/response/MyStockWatchlistResponseDTO.java
  stock-service/src/main/java/com/pda/stockservice/dto/response/StockResponseDTO.java
  stock-service/src/main/java/com/pda/stockservice/repository/FavoriteStockRepository.java
  stock-service/src/main/java/com/pda/stockservice/repository/StockCommentRepository.java
  stock-service/src/main/java/com/pda/stockservice/service/StockService.java
  stock-service/src/main/java/com/pda/stockservice/service/StockServiceImpl.java
  stock-service/src/main/resources/application.properties
  user-service/src/main/java/com/pda/userservice/controller/UserController.java
  user-service/src/main/java/com/pda/userservice/dto/response/CommentsResponseDTO.java
  user-service/src/main/java/com/pda/userservice/dto/response/FixedStockSnowflakeResponseDTO.java
  user-service/src/main/java/com/pda/userservice/dto/response/MyPortfolioCommentsResponseDTO.java
  user-service/src/main/java/com/pda/userservice/dto/response/MyStockCommentsResponseDTO.java
  user-service/src/main/java/com/pda/userservice/dto/response/MyStockWatchlistResponseDTO.java
  user-service/src/main/java/com/pda/userservice/dto/response/StocksResponseDTO.java
  user-service/src/main/java/com/pda/userservice/feign/PortfolioServiceClient.java
  user-service/src/main/java/com/pda/userservice/feign/StockServiceClient.java
  user-service/src/main/java/com/pda/userservice/jwt/LoginFilter.java
  user-service/src/main/java/com/pda/userservice/service/UserService.java
  user-service/src/main/java/com/pda/userservice/service/UserServiceImpl.java
  user-service/src/main/resources/application.properties
Labels: feat ✨

#95 pr fix(#91): 나의 포트폴리오 공유 / 삭제 API 수정
  portfolio-service/src/main/java/com/pda/portfolioservice/model/Portfolio.java
  portfolio-service/src/main/java/com/pda/portfolioservice/repository/PortfolioRepository.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioService.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioServiceImpl.java
Labels: fix 🐞

#100 Feat/#93 stock info
  stock-service/src/main/java/com/pda/stockservice/dto/response/StockInfoResponseDTO.java
  stock-service/src/main/java/com/pda/stockservice/service/StockServiceImpl.java
  user-service/src/main/java/com/pda/userservice/controller/UserController.java
Labels: feat ✨

#104 pr Feat/#96 save other portfolio search
  portfolio-service/src/main/java/com/pda/portfolioservice/controller/PortfolioController.java
  portfolio-service/src/main/java/com/pda/portfolioservice/dto/response/SaveSharePortfolioResponseDTO.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioService.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioServiceImpl.java
  stock-service/src/main/java/com/pda/stockservice/controller/StockController.java
  stock-service/src/main/java/com/pda/stockservice/dto/response/StockAutoCompleteResponseDTO.java
  stock-service/src/main/java/com/pda/stockservice/dto/response/StockSearchResponseDTO.java
  stock-service/src/main/java/com/pda/stockservice/entity/Stock.java
  stock-service/src/main/java/com/pda/stockservice/repository/StockRepository.java
  stock-service/src/main/java/com/pda/stockservice/service/StockService.java
  stock-service/src/main/java/com/pda/stockservice/service/StockServiceImpl.java
  stock-service/src/main/resources/application.properties
  user-service/src/main/resources/application.properties
Labels: feat ✨

#106 Feat/#101 get stock
  stock-service/src/main/java/com/pda/stockservice/dto/response/StockInfoResponseDTO.java
  stock-service/src/main/java/com/pda/stockservice/service/StockServiceImpl.java
Labels: feat ✨

#107 pr feat/#97-포트폴리오 평균 조회 구현
  portfolio-service/src/main/java/com/pda/portfolioservice/controller/PortfolioController.java
  portfolio-service/src/main/java/com/pda/portfolioservice/feign/StockServiceClient.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioService.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioServiceImpl.java
  portfolio-service/src/main/resources/application.properties
  stock-service/src/main/java/com/pda/stockservice/controller/StockController.java
  stock-service/src/main/java/com/pda/stockservice/dto/response/PortfolioSummaryResponseDTO.java
  stock-service/src/main/java/com/pda/stockservice/service/StockService.java
  stock-service/src/main/java/com/pda/stockservice/service/StockServiceImpl.java
Labels: feat ✨

#110 pr feat/#108-포트폴리오 평균 조회 구현
  portfolio-service/src/main/java/com/pda/portfolioservice/controller/PortfolioController.java
  portfolio-service/src/main/java/com/pda/portfolioservice/dto/response/TopPortfolioInfoResponseDTO.java
  portfolio-service/src/main/java/com/pda/portfolioservice/dto/response/TopSharePortfoliosResponseDTO.java
  portfolio-service/src/main/java/com/pda/portfolioservice/repository/SharePortfolioRepository.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioService.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioServiceImpl.java
  stock-service/src/main/java/com/pda/stockservice/controller/StockController.java
  stock-service/src/main/java/com/pda/stockservice/dto/response/ThresholdsResponseDTO.java
  stock-service/src/main/java/com/pda/stockservice/entity/StockIndicatorThresholds.java
  stock-service/src/main/java/com/pda/stockservice/repository/StockIndicatorThresholdsRepository.java
  stock-service/src/main/java/com/pda/stockservice/repository/StockRepository.java
  stock-service/src/main/java/com/pda/stockservice/service/StockService.java
  stock-service/src/main/java/com/pda/stockservice/service/StockServiceImpl.java
Labels: feat ✨

#112 "fix(#111): 경쟁사 조회"
  stock-service/src/main/java/com/pda/stockservice/repository/StockRepository.java
  stock-service/src/main/java/com/pda/stockservice/service/StockServiceImpl.java
Labels: feat ✨

#116 pr Feat/#115 my share stock graph
  stock-service/src/main/java/com/pda/stockservice/controller/StockController.java
  stock-service/src/main/java/com/pda/stockservice/dto/request/StockLineGraphRequestDTO.java
  stock-service/src/main/java/com/pda/stockservice/dto/response/StockLineGraphResponseDTO.java
  stock-service/src/main/java/com/pda/stockservice/entity/MarketIndicatorPrice.java
  stock-service/src/main/java/com/pda/stockservice/repository/MarketIndicatorPriceRepository.java
  stock-service/src/main/java/com/pda/stockservice/repository/StockPriceDayRepository.java
  stock-service/src/main/java/com/pda/stockservice/repository/StockRepository.java
  stock-service/src/main/java/com/pda/stockservice/service/StockService.java
  stock-service/src/main/java/com/pda/stockservice/service/StockServiceImpl.java
Labels: feat ✨, fix 🐞

#117 pr fix(#115): 주식 검색 자동완성 기능 파라미터 명시
  stock-service/src/main/java/com/pda/stockservice/controller/StockController.java
  stock-service/src/main/java/com/pda/stockservice/repository/StockRepository.java
Labels: fix 🐞

#119 pr Feat/#115 my share stock graph
  portfolio-service/src/main/java/com/pda/portfolioservice/controller/PortfolioController.java
  portfolio-service/src/main/java/com/pda/portfolioservice/dto/request/PortfolioMarketGraphRequestDTO.java
  portfolio-service/src/main/java/com/pda/portfolioservice/dto/response/PortfolioMarketGraphResponseDTO.java
  portfolio-service/src/main/java/com/pda/portfolioservice/enums/Market.java
  portfolio-service/src/main/java/com/pda/portfolioservice/feign/StockServiceClient.java
  portfolio-service/src/main/java/com/pda/portfolioservice/repository/MyPortfolioRepository.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioService.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioServiceImpl.java
  stock-service/src/main/java/com/pda/stockservice/controller/StockController.java
  stock-service/src/main/java/com/pda/stockservice/dto/request/PortfolioMarketGraphRequestDTO.java
  stock-service/src/main/java/com/pda/stockservice/dto/response/PortfolioMarketGraphResponseDTO.java
  stock-service/src/main/java/com/pda/stockservice/dto/response/StockLineGraphResponseDTO.java
  stock-service/src/main/java/com/pda/stockservice/repository/StockPriceDayRepository.java
  stock-service/src/main/java/com/pda/stockservice/repository/StockRepository.java
  stock-service/src/main/java/com/pda/stockservice/service/StockService.java
  stock-service/src/main/java/com/pda/stockservice/service/StockServiceImpl.java
Labels: feat ✨, fix 🐞

#124 "fix(#121): 개별종목조회 marketCap응답 추가"
  stock-service/src/main/java/com/pda/stockservice/dto/response/StockInfoResponseDTO.java
Labels: fix 🐞

#126 pr fix/#120-로그인 토큰 필터 응답 형식 수정
  api-gateway/src/main/java/com/pda/apigateway/filter/JWTFilter.java
  user-service/src/main/java/com/pda/userservice/jwt/LoginFilter.java
  user-service/src/main/java/com/pda/userservice/service/UserServiceImpl.java
Labels: fix 🐞

#130 "fix(#129): 경쟁사 조회 limit수정"
  stock-service/src/main/java/com/pda/stockservice/service/StockServiceImpl.java
Labels: fix 🐞

#131 pr feat/#120-samesite 설정 추가
  user-service/src/main/java/com/pda/userservice/jwt/LoginFilter.java
Labels: feat ✨

#132 pr fix/#120-secure 옵션 제거
  user-service/src/main/java/com/pda/userservice/jwt/LoginFilter.java
Labels: fix 🐞

#133 pr fix/#120-secure 옵션 삭제
  user-service/src/main/java/com/pda/userservice/jwt/LoginFilter.java
Labels: fix 🐞

#134 pr feat/#120-exposedHeader 설정
  api-gateway/src/main/java/com/pda/apigateway/config/SecurityConfig.java
Labels: feat ✨

#135 pr fix/#120-토큰 헤더 key값 수정
  user-service/src/main/java/com/pda/userservice/jwt/LoginFilter.java
  user-service/src/main/java/com/pda/userservice/service/UserServiceImpl.java
Labels: fix 🐞

#136 pr fix/#120-access 접근 허용
  api-gateway/src/main/java/com/pda/apigateway/config/SecurityConfig.java
Labels: fix 🐞

#137 pr test/#120-refresh test
  api-gateway/src/main/java/com/pda/apigateway/filter/JWTFilter.java
Labels: test 🙋‍♂️

#138 pr fix(#115): 개별 종목 라인그래프 컨트롤러 @PostMapping으로 수정
  stock-service/src/main/java/com/pda/stockservice/controller/StockController.java
Labels: fix 🐞

#139 pr fix(#115): 남의 포트폴리오 저장 수정
  portfolio-service/src/main/java/com/pda/portfolioservice/controller/PortfolioController.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioService.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioServiceImpl.java
Labels: fix 🐞

#140 pr fix(#115): 남의 포트폴리오 저장 코드 에러 핸들링 코드 삭제
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioServiceImpl.java
Labels: fix 🐞

#143 pr fix(#115): 공유 포트폴리오 댓글 조회 생성순 내림차순 정렬 적용
  portfolio-service/src/main/java/com/pda/portfolioservice/repository/SharePortfolioCommentRepository.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioServiceImpl.java
Labels: fix 🐞

#144 pr Feat/#115 my share stock graph
  portfolio-service/src/main/java/com/pda/portfolioservice/dto/response/SharePortfolioListResponseDTO.java
  portfolio-service/src/main/java/com/pda/portfolioservice/dto/response/SharePortfolioSummaryResponseDTO.java
  portfolio-service/src/main/java/com/pda/portfolioservice/service/PortfolioServiceImpl.java
Labels: fix 🐞

#145 pr fix(#115): 개별종목 경쟁사 조회 limit(4)로 수정
  stock-service/src/main/java/com/pda/stockservice/service/StockServiceImpl.java
Labels: fix 🐞

#148 pr fix(#115): CORS 에러 수정
  api-gateway/src/main/java/com/pda/apigateway/config/SecurityConfig.java
Labels: fix 🐞
